### ISSUE TITLE
Maybe some possible questions in your  Cpp-Primer/ch02

### ISSUE THREAD

**Issue by cxs944745612** [pezy/Cpp-Primer#15]
1.exercise 2.5   lose answer of (d)

2.exercise 2.6   your answer is “The first line's integer is decimal, the second line's integer is octal.”,    but I think second line’s first integer isn’t octal . 9 doesn’t appear in Octal like that A doesn’t appear in decimal.

3.exercise 2.27   your answer think  that  “int *const p2 = &i2” is legal,
But if i2 is a variable of double type ,what’s the answer ?so it’s not strict .
So (d),(f) have same questions ,we don’t know i2 what type it is .

4. exercise 2.31	r1 = v2 is illegal.                                    Error message : invalid initialization of reference of type 'int&' from expression of type 'const int'

My English level is very poor , so can you understand what I want to express?thanks!

**Comment by pezy** [comment]
Hi, @cxs944745612 Good to see you. :smile: 

1 and 2, you are right, and I have tried to fix it.

3. `int *const p2 = &i2`, we can judge the variable type according by it's name. Or, the question make no sense. Thus, `i2` should be an integer, rather than double as you say. 

4. I can't sure whether it will appear this error message. I am try to list the related codes as following:

```cpp
const int v2 = 0;
int v1 = v2;
int &r1 = v1;
// above is previous exercise (Exercise 2.30)
r1 = v2;
```

Use **Clang 3.5** and **gcc 4.9.2**, All passed. Could you please tell me what environment do you have? 

Thx a lot for bug reporting. :+1:

**Comment by cxs944745612** [comment]
I'm very sorry ,it's my fault .You're right!
what's more,you say"we can judge the variable type according by it's name",it means that we keep i2 as a default  integer variable .(  i: integer, d: double, f: float)
My English level is very poor , so can you understand what I want to express? I really want to say Chinese ! thanks a lot for your guidance！

**Comment by jjjasperd** [comment]
我觉着你们俩可以用中文讨论来着：）

**Comment by pezy** [comment]
@cxs944745612 @jjjasperd

那咱们以后就用中文吧～ :cn:  

> i: integer, d: double, f: float. so d2 is a double variable in c++ primer ? like this？

是的，就是这样，这本书的命名很讲究，也为初学者培养好不乱命名的好习惯。除了你提到的，第二章里，还有 `r` 代表 reference, `c` 代表 const, `p` 代表 pointer.

**Comment by cxs944745612** [comment]
好的，非常感谢！我有些新的问题请教您，我又提了两个问题在知乎上邀请您回答了，如果有时间的话，麻烦您了。

**Comment by pezy** [comment]
@cxs944745612 真的抱歉，周末有些事耽搁了，明天我帮你看看～ :horse_racing:

**Comment by cxs944745612** [comment]
没事没事，您有时间就看，非常感谢您的无私帮助！
